### ISSUE TITLE
Hide PR failures by default

### ISSUE THREAD

**Issue by akoeplinger** [xamarin/mono-test-results#3]
Failures in PRs can be due to a number of reasons (e.g. legit failures due to a bug in the implementation) which aren't interesting for finding flaky tests.

**Comment by xmcclure** [comment]
Do you mean, show/hide on the PR filter should default to Hide? Or something else?

**Comment by akoeplinger** [comment]
Yes, default to hide.

**Comment by akoeplinger** [comment]
It's defaulting to Hide now.
